// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pO0V7-c_L8qv1On4RCvCjJQgMKEotmA',
    appId: '1:802213364546:web:e9f4f8a950017e86d53edb',
    messagingSenderId: '802213364546',
    projectId: 'btl-test-ea331',
    authDomain: 'btl-test-ea331.firebaseapp.com',
    storageBucket: 'btl-test-ea331.firebasestorage.app',
    measurementId: 'G-J27RMQ5E44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPjpuCW4pr2SwoBFJ7gH9g8wpxk58cAsQ',
    appId: '1:802213364546:android:a575a9d4387ce3f0d53edb',
    messagingSenderId: '802213364546',
    projectId: 'btl-test-ea331',
    storageBucket: 'btl-test-ea331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXj7KOBZaIanAuABRh2ee1dxYHYLbclRk',
    appId: '1:802213364546:ios:e82b3ae4db290910d53edb',
    messagingSenderId: '802213364546',
    projectId: 'btl-test-ea331',
    storageBucket: 'btl-test-ea331.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXj7KOBZaIanAuABRh2ee1dxYHYLbclRk',
    appId: '1:802213364546:ios:e82b3ae4db290910d53edb',
    messagingSenderId: '802213364546',
    projectId: 'btl-test-ea331',
    storageBucket: 'btl-test-ea331.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7pO0V7-c_L8qv1On4RCvCjJQgMKEotmA',
    appId: '1:802213364546:web:efcded81a0dbcf63d53edb',
    messagingSenderId: '802213364546',
    projectId: 'btl-test-ea331',
    authDomain: 'btl-test-ea331.firebaseapp.com',
    storageBucket: 'btl-test-ea331.firebasestorage.app',
    measurementId: 'G-N5TFL7ESKK',
  );

}