// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWkuLw8E58cYqtOqKCSgMfNfHMZOZY7vk',
    appId: '1:676439085609:web:b21204aa2c31516913c238',
    messagingSenderId: '676439085609',
    projectId: 'hcmut-app',
    authDomain: 'hcmut-app.firebaseapp.com',
    storageBucket: 'hcmut-app.firebasestorage.app',
    measurementId: 'G-ZZ00GD315B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMl0pBaFgSTj-qsTjG2ZlwJQr0F9a6GT4',
    appId: '1:676439085609:android:5780249c562b83cb13c238',
    messagingSenderId: '676439085609',
    projectId: 'hcmut-app',
    storageBucket: 'hcmut-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdW1GpO0AiK-nsg_SkHusKJSbwY1KZ50',
    appId: '1:676439085609:ios:08f43f434e8953c313c238',
    messagingSenderId: '676439085609',
    projectId: 'hcmut-app',
    storageBucket: 'hcmut-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdW1GpO0AiK-nsg_SkHusKJSbwY1KZ50',
    appId: '1:676439085609:ios:08f43f434e8953c313c238',
    messagingSenderId: '676439085609',
    projectId: 'hcmut-app',
    storageBucket: 'hcmut-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWkuLw8E58cYqtOqKCSgMfNfHMZOZY7vk',
    appId: '1:676439085609:web:cba4f0974592302d13c238',
    messagingSenderId: '676439085609',
    projectId: 'hcmut-app',
    authDomain: 'hcmut-app.firebaseapp.com',
    storageBucket: 'hcmut-app.firebasestorage.app',
    measurementId: 'G-Y470EKQ2TG',
  );
}
